# Notice how we put your Render Hostname right after jdbc:postgresql://
spring.datasource.url=jdbc:postgresql://dpg-d88oiobbc2fs73efe45g-a:5432/hospital_db_274h
spring.datasource.username=hospital_db_274h_user
spring.datasource.password=2kCykMzXcPV4QYzYHpqagvPP3aKiYWtV

# This tells Spring Boot to create the tables in the cloud if they are missing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true